const townArea = document.getElementById('town-area');
const town = document.getElementById('populated-place');


town.addEventListener('change', AddProperRegion)

function AddProperRegion(){
    // const townOption = townArea.getElementsByTagName('option');
    switch(town.value){
        case 'tblagoevgrad':
            townArea.innerHTML = `
            <option value="">Ален мак</option>
            <option value="">Балабарши</option>
            <option value="">Бялата висота</option>
            <option value="">Вароша</option>
            <option value="">Втора промишлена зона</option>
            <option value="">Грамада</option>
            <option value="">Еленово 1</option>
            <option value="">Еленово 2</option>
            <option value="">Запад</option>
            <option value="">Идеален център</option>
            <option value="">Орлова чука</option>
            <option value="">Освобождение</option>
            <option value="">Първа промишлена зона</option>
            <option value="">Струмско</option>
            <option value="">Широк център</option>`
        break;

        case 'pblagoevgrad':
            townArea.innerHTML = `
            <option value="главен път Е79">главен път Е79
            <option value="гр. Банско">гр. Банско
            <option value="гр. Белица">гр. Белица
            <option value="гр. Гоце Делчев">гр. Гоце Делчев
            <option value="гр. Добринище">гр. Добринище
            <option value="гр. Кресна">гр. Кресна
            <option value="гр. Мелник">гр. Мелник
            <option value="гр. Петрич">гр. Петрич
            <option value="гр. Разлог">гр. Разлог
            <option value="гр. Сандански">гр. Сандански
            <option value="гр. Симитли">гр. Симитли
            <option value="гр. Хаджидимово">гр. Хаджидимово
            <option value="гр. Якоруда">гр. Якоруда
            <option value="с. Абланица">с. Абланица
            <option value="с. Аврамово">с. Аврамово
            <option value="с. Бабяк">с. Бабяк
            <option value="с. Балдево">с. Балдево
            <option value="с. Баничан">с. Баничан
            <option value="с. Баня">с. Баня
            <option value="с. Баскалци">с. Баскалци
            <option value="с. Бачево">с. Бачево
            <option value="с. Бел камен">с. Бел камен
            <option value="с. Беласица">с. Беласица
            <option value="с. Бело поле">с. Бело поле
            <option value="с. Бельово">с. Бельово
            <option value="с. Беслен">с. Беслен
            <option value="с. Бистрица">с. Бистрица
            <option value="с. Блатска">с. Блатска
            <option value="с. Боголин">с. Боголин
            <option value="с. Богородица">с. Богородица
            <option value="с. Бождово">с. Бождово
            <option value="с. Боровичене">с. Боровичене
            <option value="с. Борово">с. Борово
            <option value="с. Брежани">с. Брежани
            <option value="с. Брезница">с. Брезница
            <option value="с. Брестово">с. Брестово
            <option value="с. Будилци">с. Будилци
            <option value="с. Буково">с. Буково
            <option value="с. Бунцево">с. Бунцево
            <option value="с. Бучино">с. Бучино
            <option value="с. Българчево">с. Българчево
            <option value="с. Ваклиново">с. Ваклиново
            <option value="с. Велющец">с. Велющец
            <option value="с. Виногради">с. Виногради
            <option value="с. Вихрен">с. Вихрен
            <option value="с. Вишлене">с. Вишлене
            <option value="с. Влахи">с. Влахи
            <option value="с. Волно">с. Волно
            <option value="с. Вракуповица">с. Вракуповица
            <option value="с. Враня">с. Враня
            <option value="с. Вълково">с. Вълково
            <option value="с. Вълкосел">с. Вълкосел
            <option value="с. Габрене">с. Габрене
            <option value="с. Габрово">с. Габрово
            <option value="с. Гайтаниново">с. Гайтаниново
            <option value="с. Гега">с. Гега
            <option value="с. Генерал Тодоров">с. Генерал Тодоров
            <option value="с. Годешево">с. Годешево
            <option value="с. Годлево">с. Годлево
            <option value="с. Голем Цалим">с. Голем Цалим
            <option value="с. Голешово">с. Голешово
            <option value="с. Гореме">с. Гореме
            <option value="с. Горна Брезница">с. Горна Брезница
            <option value="с. Горна Крушица">с. Горна Крушица
            <option value="с. Горна Рибница">с. Горна Рибница
            <option value="с. Горна Сушица">с. Горна Сушица
            <option value="с. Горно Драглище">с. Горно Драглище
            <option value="с. Горно Дряново">с. Горно Дряново
            <option value="с. Горно Краище">с. Горно Краище
            <option value="с. Горно Осеново">с. Горно Осеново
            <option value="с. Горно Спанчево">с. Горно Спанчево
            <option value="с. Горно Хърсово">с. Горно Хърсово
            <option value="с. Горчево">с. Горчево
            <option value="с. Господинци">с. Господинци
            <option value="с. Гостун">с. Гостун
            <option value="с. Градево">с. Градево
            <option value="с. Гълъбово">с. Гълъбово
            <option value="с. Гърмен">с. Гърмен
            <option value="с. Гюргево">с. Гюргево
            <option value="с. Дагоново">с. Дагоново
            <option value="с. Дамяница">с. Дамяница
            <option value="с. Дебочица">с. Дебочица
            <option value="с. Дебрен">с. Дебрен
            <option value="с. Дебрене">с. Дебрене
            <option value="с. Делвино">с. Делвино
            <option value="с. Делчево">с. Делчево
            <option value="с. Джигурово">с. Джигурово
            <option value="с. Добри лаки">с. Добри лаки
            <option value="с. Добротино">с. Добротино
            <option value="с. Добърско">с. Добърско
            <option value="с. Докатичево">с. Докатичево
            <option value="с. Долен">с. Долен
            <option value="с. Долене">с. Долене
            <option value="с. Долени">с. Долени
            <option value="с. Долна Градешница">с. Долна Градешница
            <option value="с. Долна Крушица">с. Долна Крушица
            <option value="с. Долна Рибница">с. Долна Рибница
            <option value="с. Долно Драглище">с. Долно Драглище
            <option value="с. Долно Дряново">с. Долно Дряново
            <option value="с. Долно Осеново">с. Долно Осеново
            <option value="с. Долно Спанчево">с. Долно Спанчево
            <option value="с. Драгуш">с. Драгуш
            <option value="с. Драката">с. Драката
            <option value="с. Дрангово">с. Дрангово
            <option value="с. Дренково">с. Дренково
            <option value="с. Дреновица">с. Дреновица
            <option value="с. Дреново">с. Дреново
            <option value="с. Дъбница">с. Дъбница
            <option value="с. Дъбрава">с. Дъбрава
            <option value="с. Езерец">с. Езерец
            <option value="с. Еленово">с. Еленово
            <option value="с. Елешница">с. Елешница
            <option value="с. Железница">с. Железница
            <option value="с. Жижево">с. Жижево
            <option value="с. Занога">с. Занога
            <option value="с. Зелендол">с. Зелендол
            <option value="с. Златарица">с. Златарица
            <option value="с. Златолист">с. Златолист
            <option value="с. Зойчене">с. Зойчене
            <option value="с. Зорница">с. Зорница
            <option value="с. Иваново">с. Иваново
            <option value="с. Игралище">с. Игралище
            <option value="с. Изгрев">с. Изгрев
            <option value="с. Илинден">с. Илинден
            <option value="с. Илинденци">с. Илинденци
            <option value="с. Кавракирово">с. Кавракирово
            <option value="с. Калиманци">с. Калиманци
            <option value="с. Камена">с. Камена
            <option value="с. Каменица">с. Каменица
            <option value="с. Капатово">с. Капатово
            <option value="с. Катунци">с. Катунци
            <option value="с. Кашина">с. Кашина
            <option value="с. Кладенци">с. Кладенци
            <option value="с. Клепало">с. Клепало
            <option value="с. Клисура">с. Клисура
            <option value="с. Ключ">с. Ключ
            <option value="с. Ковачевица">с. Ковачевица
            <option value="с. Ковачево">с. Ковачево
            <option value="с. Коларово">с. Коларово
            <option value="с. Колибите">с. Колибите
            <option value="с. Конарско">с. Конарско
            <option value="с. Копривлен">с. Копривлен
            <option value="с. Корница">с. Корница
            <option value="с. Кочан">с. Кочан
            <option value="с. Краище">с. Краище
            <option value="с. Кремен">с. Кремен
            <option value="с. Крибул">с. Крибул
            <option value="с. Кромидово">с. Кромидово
            <option value="с. Крупник">с. Крупник
            <option value="с. Крушево">с. Крушево
            <option value="с. Крънджилица">с. Крънджилица
            <option value="с. Кръстилци">с. Кръстилци
            <option value="с. Кузьово">с. Кузьово
            <option value="с. Кукурахцево">с. Кукурахцево
            <option value="с. Кулата">с. Кулата
            <option value="с. Кърланово">с. Кърланово
            <option value="с. Кърналово">с. Кърналово
            <option value="с. Кърпелево">с. Кърпелево
            <option value="с. Ладарево">с. Ладарево
            <option value="с. Ласкарево">с. Ласкарево
            <option value="с. Лебница">с. Лебница
            <option value="с. Левуново">с. Левуново
            <option value="с. Лехово">с. Лехово
            <option value="с. Лешко">с. Лешко
            <option value="с. Лешница">с. Лешница
            <option value="с. Лещен">с. Лещен
            <option value="с. Лиляново">с. Лиляново
            <option value="с. Лисия">с. Лисия
            <option value="с. Логодаж">с. Логодаж
            <option value="с. Лозеница">с. Лозеница
            <option value="с. Лъжница">с. Лъжница
            <option value="с. Лъки">с. Лъки
            <option value="с. Любовище">с. Любовище
            <option value="с. Любовка">с. Любовка
            <option value="с. Лютово">с. Лютово
            <option value="с. Малки Цалим">с. Малки Цалим
            <option value="с. Марикостиново">с. Марикостиново
            <option value="с. Марино поле">с. Марино поле
            <option value="с. Марулево">с. Марулево
            <option value="с. Марчево">с. Марчево
            <option value="с. Махалата">с. Махалата
            <option value="с. Мендово">с. Мендово
            <option value="с. Места">с. Места
            <option value="с. Мечкул">с. Мечкул
            <option value="с. Микрево">с. Микрево
            <option value="с. Митино">с. Митино
            <option value="с. Михнево">с. Михнево
            <option value="с. Мощанец">с. Мощанец
            <option value="с. Мусомища">с. Мусомища
            <option value="с. Никудин">с. Никудин
            <option value="с. Нова Ловча">с. Нова Ловча
            <option value="с. Ново Делчево">с. Ново Делчево
            <option value="с. Ново Кономлади">с. Ново Кономлади
            <option value="с. Ново Лески">с. Ново Лески
            <option value="с. Ново село">с. Ново село
            <option value="с. Ново Ходжово">с. Ново Ходжово
            <option value="с. Обел">с. Обел
            <option value="с. Обидим">с. Обидим
            <option value="с. Огняново">с. Огняново
            <option value="с. Ореше">с. Ореше
            <option value="с. Орцево">с. Орцево
            <option value="с. Осеново">с. Осеново
            <option value="с. Осиково">с. Осиково
            <option value="с. Осина">с. Осина
            <option value="с. Ощава">с. Ощава
            <option value="с. Падеш">с. Падеш
            <option value="с. Палат">с. Палат
            <option value="с. Палатик">с. Палатик
            <option value="с. Парил">с. Парил
            <option value="с. Петрелик">с. Петрелик
            <option value="с. Петрово">с. Петрово
            <option value="с. Пиперица">с. Пиперица
            <option value="с. Пирин">с. Пирин
            <option value="с. Плетена">с. Плетена
            <option value="с. Плоски">с. Плоски
            <option value="с. Покровник">с. Покровник
            <option value="с. Полена">с. Полена
            <option value="с. Поленица">с. Поленица
            <option value="с. Полето">с. Полето
            <option value="с. Право бърдо">с. Право бърдо
            <option value="с. Първомай">с. Първомай
            <option value="с. Раздол">с. Раздол
            <option value="с. Ракитна">с. Ракитна
            <option value="с. Рибник">с. Рибник
            <option value="с. Рибново">с. Рибново
            <option value="с. Рилци">с. Рилци
            <option value="с. Рожен">с. Рожен
            <option value="с. Рупите">с. Рупите
            <option value="с. Ръждак">с. Ръждак
            <option value="с. Садово">с. Садово
            <option value="с. Самуилова крепост">с. Самуилова крепост
            <option value="с. Самуилово">с. Самуилово
            <option value="с. Сатовча">с. Сатовча
            <option value="с. Седелец">с. Седелец
            <option value="с. Селище">с. Селище
            <option value="с. Сенокос">с. Сенокос
            <option value="с. Склаве">с. Склаве
            <option value="с. Скребатно">с. Скребатно
            <option value="с. Скрът">с. Скрът
            <option value="с. Слащен">с. Слащен
            <option value="с. Сливница">с. Сливница
            <option value="с. Смолево">с. Смолево
            <option value="с. Спатово">с. Спатово
            <option value="с. Стара Кресна">с. Стара Кресна
            <option value="с. Старчево">с. Старчево
            <option value="с. Стожа">с. Стожа
            <option value="с. Струма">с. Струма
            <option value="с. Струмешница">с. Струмешница
            <option value="с. Струмяни">с. Струмяни
            <option value="с. Сугарево">с. Сугарево
            <option value="с. Сухострел">с. Сухострел
            <option value="с. Сушица">с. Сушица
            <option value="с. Теплен">с. Теплен
            <option value="с. Тешово">с. Тешово
            <option value="с. Тонско дабе">с. Тонско дабе
            <option value="с. Тополница">с. Тополница
            <option value="с. Тросково">с. Тросково
            <option value="с. Туховища">с. Туховища
            <option value="с. Филипово">с. Филипово
            <option value="с. Фъргово">с. Фъргово
            <option value="с. Хвостяне">с. Хвостяне
            <option value="с. Хотово">с. Хотово
            <option value="с. Храсна">с. Храсна
            <option value="с. Хърсово">с. Хърсово
            <option value="с. Цапарево">с. Цапарево
            <option value="с. Церово">с. Церово
            <option value="с. Черешница">с. Черешница
            <option value="с. Черешово">с. Черешово
            <option value="с. Черна Места">с. Черна Места
            <option value="с. Черниче">с. Черниче
            <option value="с. Чурилово">с. Чурилово
            <option value="с. Чуричени">с. Чуричени
            <option value="с. Чучулигово">с. Чучулигово
            <option value="с. Юруково">с. Юруково
            <option value="с. Яворница">с. Яворница
            <option value="с. Яково">с. Яково
            <option value="с. Яново">с. Яново
            
             `
        break;
    }


}