const townArea = document.getElementById('town-area');
const town = document.getElementById('populated-place');


town.addEventListener('change', AddProperRegion)

function AddProperRegion(){
    // const townOption = townArea.getElementsByTagName('option');
    switch(town.value){
        case 'tblagoevgrad':
            townArea.innerHTML = `
            <option value="">Ален мак</option>
            <option value="">Балабарши</option>
            <option value="">Бялата висота</option>
            <option value="">Вароша</option>
            <option value="">Втора промишлена зона</option>
            <option value="">Грамада</option>
            <option value="">Еленово 1</option>
            <option value="">Еленово 2</option>
            <option value="">Запад</option>
            <option value="">Идеален център</option>
            <option value="">Орлова чука</option>
            <option value="">Освобождение</option>
            <option value="">Първа промишлена зона</option>
            <option value="">Струмско</option>
            <option value="">Широк център</option>`
        break;

        case 'pblagoevgrad':
            townArea.innerHTML = `
            <option value="главен път Е79">главен път Е79
            <option value="гр. Банско">гр. Банско
            <option value="гр. Белица">гр. Белица
            <option value="гр. Гоце Делчев">гр. Гоце Делчев
            <option value="гр. Добринище">гр. Добринище
            <option value="гр. Кресна">гр. Кресна
            <option value="гр. Мелник">гр. Мелник
            <option value="гр. Петрич">гр. Петрич
            <option value="гр. Разлог">гр. Разлог
            <option value="гр. Сандански">гр. Сандански
            <option value="гр. Симитли">гр. Симитли
            <option value="гр. Хаджидимово">гр. Хаджидимово
            <option value="гр. Якоруда">гр. Якоруда
            <option value="с. Абланица">с. Абланица
            <option value="с. Аврамово">с. Аврамово
            <option value="с. Бабяк">с. Бабяк
            <option value="с. Балдево">с. Балдево
            <option value="с. Баничан">с. Баничан
            <option value="с. Баня">с. Баня
            <option value="с. Баскалци">с. Баскалци
            <option value="с. Бачево">с. Бачево
            <option value="с. Бел камен">с. Бел камен
            <option value="с. Беласица">с. Беласица
            <option value="с. Бело поле">с. Бело поле
            <option value="с. Бельово">с. Бельово
            <option value="с. Беслен">с. Беслен
            <option value="с. Бистрица">с. Бистрица
            <option value="с. Блатска">с. Блатска
            <option value="с. Боголин">с. Боголин
            <option value="с. Богородица">с. Богородица
            <option value="с. Бождово">с. Бождово
            <option value="с. Боровичене">с. Боровичене
            <option value="с. Борово">с. Борово
            <option value="с. Брежани">с. Брежани
            <option value="с. Брезница">с. Брезница
            <option value="с. Брестово">с. Брестово
            <option value="с. Будилци">с. Будилци
            <option value="с. Буково">с. Буково
            <option value="с. Бунцево">с. Бунцево
            <option value="с. Бучино">с. Бучино
            <option value="с. Българчево">с. Българчево
            <option value="с. Ваклиново">с. Ваклиново
            <option value="с. Велющец">с. Велющец
            <option value="с. Виногради">с. Виногради
            <option value="с. Вихрен">с. Вихрен
            <option value="с. Вишлене">с. Вишлене
            <option value="с. Влахи">с. Влахи
            <option value="с. Волно">с. Волно
            <option value="с. Вракуповица">с. Вракуповица
            <option value="с. Враня">с. Враня
            <option value="с. Вълково">с. Вълково
            <option value="с. Вълкосел">с. Вълкосел
            <option value="с. Габрене">с. Габрене
            <option value="с. Габрово">с. Габрово
            <option value="с. Гайтаниново">с. Гайтаниново
            <option value="с. Гега">с. Гега
            <option value="с. Генерал Тодоров">с. Генерал Тодоров
            <option value="с. Годешево">с. Годешево
            <option value="с. Годлево">с. Годлево
            <option value="с. Голем Цалим">с. Голем Цалим
            <option value="с. Голешово">с. Голешово
            <option value="с. Гореме">с. Гореме
            <option value="с. Горна Брезница">с. Горна Брезница
            <option value="с. Горна Крушица">с. Горна Крушица
            <option value="с. Горна Рибница">с. Горна Рибница
            <option value="с. Горна Сушица">с. Горна Сушица
            <option value="с. Горно Драглище">с. Горно Драглище
            <option value="с. Горно Дряново">с. Горно Дряново
            <option value="с. Горно Краище">с. Горно Краище
            <option value="с. Горно Осеново">с. Горно Осеново
            <option value="с. Горно Спанчево">с. Горно Спанчево
            <option value="с. Горно Хърсово">с. Горно Хърсово
            <option value="с. Горчево">с. Горчево
            <option value="с. Господинци">с. Господинци
            <option value="с. Гостун">с. Гостун
            <option value="с. Градево">с. Градево
            <option value="с. Гълъбово">с. Гълъбово
            <option value="с. Гърмен">с. Гърмен
            <option value="с. Гюргево">с. Гюргево
            <option value="с. Дагоново">с. Дагоново
            <option value="с. Дамяница">с. Дамяница
            <option value="с. Дебочица">с. Дебочица
            <option value="с. Дебрен">с. Дебрен
            <option value="с. Дебрене">с. Дебрене
            <option value="с. Делвино">с. Делвино
            <option value="с. Делчево">с. Делчево
            <option value="с. Джигурово">с. Джигурово
            <option value="с. Добри лаки">с. Добри лаки
            <option value="с. Добротино">с. Добротино
            <option value="с. Добърско">с. Добърско
            <option value="с. Докатичево">с. Докатичево
            <option value="с. Долен">с. Долен
            <option value="с. Долене">с. Долене
            <option value="с. Долени">с. Долени
            <option value="с. Долна Градешница">с. Долна Градешница
            <option value="с. Долна Крушица">с. Долна Крушица
            <option value="с. Долна Рибница">с. Долна Рибница
            <option value="с. Долно Драглище">с. Долно Драглище
            <option value="с. Долно Дряново">с. Долно Дряново
            <option value="с. Долно Осеново">с. Долно Осеново
            <option value="с. Долно Спанчево">с. Долно Спанчево
            <option value="с. Драгуш">с. Драгуш
            <option value="с. Драката">с. Драката
            <option value="с. Дрангово">с. Дрангово
            <option value="с. Дренково">с. Дренково
            <option value="с. Дреновица">с. Дреновица
            <option value="с. Дреново">с. Дреново
            <option value="с. Дъбница">с. Дъбница
            <option value="с. Дъбрава">с. Дъбрава
            <option value="с. Езерец">с. Езерец
            <option value="с. Еленово">с. Еленово
            <option value="с. Елешница">с. Елешница
            <option value="с. Железница">с. Железница
            <option value="с. Жижево">с. Жижево
            <option value="с. Занога">с. Занога
            <option value="с. Зелендол">с. Зелендол
            <option value="с. Златарица">с. Златарица
            <option value="с. Златолист">с. Златолист
            <option value="с. Зойчене">с. Зойчене
            <option value="с. Зорница">с. Зорница
            <option value="с. Иваново">с. Иваново
            <option value="с. Игралище">с. Игралище
            <option value="с. Изгрев">с. Изгрев
            <option value="с. Илинден">с. Илинден
            <option value="с. Илинденци">с. Илинденци
            <option value="с. Кавракирово">с. Кавракирово
            <option value="с. Калиманци">с. Калиманци
            <option value="с. Камена">с. Камена
            <option value="с. Каменица">с. Каменица
            <option value="с. Капатово">с. Капатово
            <option value="с. Катунци">с. Катунци
            <option value="с. Кашина">с. Кашина
            <option value="с. Кладенци">с. Кладенци
            <option value="с. Клепало">с. Клепало
            <option value="с. Клисура">с. Клисура
            <option value="с. Ключ">с. Ключ
            <option value="с. Ковачевица">с. Ковачевица
            <option value="с. Ковачево">с. Ковачево
            <option value="с. Коларово">с. Коларово
            <option value="с. Колибите">с. Колибите
            <option value="с. Конарско">с. Конарско
            <option value="с. Копривлен">с. Копривлен
            <option value="с. Корница">с. Корница
            <option value="с. Кочан">с. Кочан
            <option value="с. Краище">с. Краище
            <option value="с. Кремен">с. Кремен
            <option value="с. Крибул">с. Крибул
            <option value="с. Кромидово">с. Кромидово
            <option value="с. Крупник">с. Крупник
            <option value="с. Крушево">с. Крушево
            <option value="с. Крънджилица">с. Крънджилица
            <option value="с. Кръстилци">с. Кръстилци
            <option value="с. Кузьово">с. Кузьово
            <option value="с. Кукурахцево">с. Кукурахцево
            <option value="с. Кулата">с. Кулата
            <option value="с. Кърланово">с. Кърланово
            <option value="с. Кърналово">с. Кърналово
            <option value="с. Кърпелево">с. Кърпелево
            <option value="с. Ладарево">с. Ладарево
            <option value="с. Ласкарево">с. Ласкарево
            <option value="с. Лебница">с. Лебница
            <option value="с. Левуново">с. Левуново
            <option value="с. Лехово">с. Лехово
            <option value="с. Лешко">с. Лешко
            <option value="с. Лешница">с. Лешница
            <option value="с. Лещен">с. Лещен
            <option value="с. Лиляново">с. Лиляново
            <option value="с. Лисия">с. Лисия
            <option value="с. Логодаж">с. Логодаж
            <option value="с. Лозеница">с. Лозеница
            <option value="с. Лъжница">с. Лъжница
            <option value="с. Лъки">с. Лъки
            <option value="с. Любовище">с. Любовище
            <option value="с. Любовка">с. Любовка
            <option value="с. Лютово">с. Лютово
            <option value="с. Малки Цалим">с. Малки Цалим
            <option value="с. Марикостиново">с. Марикостиново
            <option value="с. Марино поле">с. Марино поле
            <option value="с. Марулево">с. Марулево
            <option value="с. Марчево">с. Марчево
            <option value="с. Махалата">с. Махалата
            <option value="с. Мендово">с. Мендово
            <option value="с. Места">с. Места
            <option value="с. Мечкул">с. Мечкул
            <option value="с. Микрево">с. Микрево
            <option value="с. Митино">с. Митино
            <option value="с. Михнево">с. Михнево
            <option value="с. Мощанец">с. Мощанец
            <option value="с. Мусомища">с. Мусомища
            <option value="с. Никудин">с. Никудин
            <option value="с. Нова Ловча">с. Нова Ловча
            <option value="с. Ново Делчево">с. Ново Делчево
            <option value="с. Ново Кономлади">с. Ново Кономлади
            <option value="с. Ново Лески">с. Ново Лески
            <option value="с. Ново село">с. Ново село
            <option value="с. Ново Ходжово">с. Ново Ходжово
            <option value="с. Обел">с. Обел
            <option value="с. Обидим">с. Обидим
            <option value="с. Огняново">с. Огняново
            <option value="с. Ореше">с. Ореше
            <option value="с. Орцево">с. Орцево
            <option value="с. Осеново">с. Осеново
            <option value="с. Осиково">с. Осиково
            <option value="с. Осина">с. Осина
            <option value="с. Ощава">с. Ощава
            <option value="с. Падеш">с. Падеш
            <option value="с. Палат">с. Палат
            <option value="с. Палатик">с. Палатик
            <option value="с. Парил">с. Парил
            <option value="с. Петрелик">с. Петрелик
            <option value="с. Петрово">с. Петрово
            <option value="с. Пиперица">с. Пиперица
            <option value="с. Пирин">с. Пирин
            <option value="с. Плетена">с. Плетена
            <option value="с. Плоски">с. Плоски
            <option value="с. Покровник">с. Покровник
            <option value="с. Полена">с. Полена
            <option value="с. Поленица">с. Поленица
            <option value="с. Полето">с. Полето
            <option value="с. Право бърдо">с. Право бърдо
            <option value="с. Първомай">с. Първомай
            <option value="с. Раздол">с. Раздол
            <option value="с. Ракитна">с. Ракитна
            <option value="с. Рибник">с. Рибник
            <option value="с. Рибново">с. Рибново
            <option value="с. Рилци">с. Рилци
            <option value="с. Рожен">с. Рожен
            <option value="с. Рупите">с. Рупите
            <option value="с. Ръждак">с. Ръждак
            <option value="с. Садово">с. Садово
            <option value="с. Самуилова крепост">с. Самуилова крепост
            <option value="с. Самуилово">с. Самуилово
            <option value="с. Сатовча">с. Сатовча
            <option value="с. Седелец">с. Седелец
            <option value="с. Селище">с. Селище
            <option value="с. Сенокос">с. Сенокос
            <option value="с. Склаве">с. Склаве
            <option value="с. Скребатно">с. Скребатно
            <option value="с. Скрът">с. Скрът
            <option value="с. Слащен">с. Слащен
            <option value="с. Сливница">с. Сливница
            <option value="с. Смолево">с. Смолево
            <option value="с. Спатово">с. Спатово
            <option value="с. Стара Кресна">с. Стара Кресна
            <option value="с. Старчево">с. Старчево
            <option value="с. Стожа">с. Стожа
            <option value="с. Струма">с. Струма
            <option value="с. Струмешница">с. Струмешница
            <option value="с. Струмяни">с. Струмяни
            <option value="с. Сугарево">с. Сугарево
            <option value="с. Сухострел">с. Сухострел
            <option value="с. Сушица">с. Сушица
            <option value="с. Теплен">с. Теплен
            <option value="с. Тешово">с. Тешово
            <option value="с. Тонско дабе">с. Тонско дабе
            <option value="с. Тополница">с. Тополница
            <option value="с. Тросково">с. Тросково
            <option value="с. Туховища">с. Туховища
            <option value="с. Филипово">с. Филипово
            <option value="с. Фъргово">с. Фъргово
            <option value="с. Хвостяне">с. Хвостяне
            <option value="с. Хотово">с. Хотово
            <option value="с. Храсна">с. Храсна
            <option value="с. Хърсово">с. Хърсово
            <option value="с. Цапарево">с. Цапарево
            <option value="с. Церово">с. Церово
            <option value="с. Черешница">с. Черешница
            <option value="с. Черешово">с. Черешово
            <option value="с. Черна Места">с. Черна Места
            <option value="с. Черниче">с. Черниче
            <option value="с. Чурилово">с. Чурилово
            <option value="с. Чуричени">с. Чуричени
            <option value="с. Чучулигово">с. Чучулигово
            <option value="с. Юруково">с. Юруково
            <option value="с. Яворница">с. Яворница
            <option value="с. Яково">с. Яково
            <option value="с. Яново">с. Яново
            
             `
        break;
        case 'tburgas':
            townArea.innerHTML = `
            <option value="Акациите">Акациите
            <option value="Банево">Банево
            <option value="Братя Миладинови">Братя Миладинови
            <option value="Ветрен">Ветрен
            <option value="Възраждане">Възраждане
            <option value="Горно Езерово">Горно Езерово
            <option value="Долно Езерово">Долно Езерово
            <option value="Зорница">Зорница
            <option value="Изгрев">Изгрев
            <option value="Крайморие">Крайморие
            <option value="Лазур">Лазур
            <option value="Летище Бургас">Летище Бургас
            <option value="Лозово">Лозово
            <option value="Меден рудник - зона А">Меден рудник - зона А
            <option value="Меден рудник - зона Б">Меден рудник - зона Б
            <option value="Меден рудник - зона В">Меден рудник - зона В
            <option value="Меден рудник - зона Г">Меден рудник - зона Г
            <option value="Меден рудник - зона Д">Меден рудник - зона Д
            <option value="Пети километър">Пети километър
            <option value="Победа">Победа
            <option value="Пристанище Бургас">Пристанище Бургас
            <option value="Промишлена зона - Лозово">Промишлена зона - Лозово
            <option value="Промишлена зона - Север">Промишлена зона - Север
            <option value="Промишлена зона - Юг">Промишлена зона - Юг
            <option value="Рудник">Рудник
            <option value="Сарафово">Сарафово
            <option value="Свобода">Свобода
            <option value="Славейков">Славейков
            <option value="Център">Център
            <option value="Черно море">Черно море
            <option value="в.з.Боровете">в.з.Боровете
            <option value="в.з.Брястовете">в.з.Брястовете
            <option value="в.з.Димчево">в.з.Димчево
            <option value="в.з.Лозницата">в.з.Лозницата
            <option value="в.з.Острица">в.з.Острица
            <option value="в.з.Черниците">в.з.Черниците
            <option value="гр. Българово">гр. Българово
            <option value="м-ст Бадемите">м-ст Бадемите
            <option value="м-ст Батака">м-ст Батака
            <option value="м-ст Върли Бряг">м-ст Върли Бряг
            <option value="м-ст Каменица">м-ст Каменица
            <option value="м-ст Каптажа">м-ст Каптажа
            <option value="м-ст Капчето">м-ст Капчето
            <option value="м-ст Минерални бани">м-ст Минерални бани
            <option value="м-ст Отманли">м-ст Отманли
            <option value="м-ст Погребите">м-ст Погребите
            <option value="м-ст Сухото дере">м-ст Сухото дере
            <option value="м-ст Ченгене Скеле">м-ст Ченгене Скеле
            <option value="м-ст Червени Рид">м-ст Червени Рид
            <option value="м-ст Шилото">м-ст Шилото
            <option value="с. Братово">с. Братово
            <option value="с. Брястовец">с. Брястовец
            <option value="с. Димчево">с. Димчево
            <option value="с. Драганово">с. Драганово
            <option value="с. Извор">с. Извор
            <option value="с. Изворище">с. Изворище
            <option value="с. Маринка">с. Маринка
            <option value="с. Миролюбово">с. Миролюбово
            <option value="с. Равнец">с. Равнец
            <option value="с. Твърдица">с. Твърдица`
        break;

        case 'pburgas':
            textArea.innerHTML = `
            <option value="гр. Айтос">гр. Айтос
            <option value="гр. Ахелой">гр. Ахелой
            <option value="гр. Ахтопол">гр. Ахтопол
            <option value="гр. Каблешково">гр. Каблешково
            <option value="гр. Камено">гр. Камено
            <option value="гр. Карнобат">гр. Карнобат
            <option value="гр. Китен">гр. Китен
            <option value="гр. Малко Търново">гр. Малко Търново
            <option value="гр. Несебър">гр. Несебър
            <option value="гр. Обзор">гр. Обзор
            <option value="гр. Поморие">гр. Поморие
            <option value="гр. Приморско">гр. Приморско
            <option value="гр. Свети Влас">гр. Свети Влас
            <option value="гр. Созопол">гр. Созопол
            <option value="гр. Средец">гр. Средец
            <option value="гр. Сунгурларе">гр. Сунгурларе
            <option value="гр. Царево">гр. Царево
            <option value="гр. Черноморец">гр. Черноморец
            <option value="к.к. Дюни">к.к. Дюни
            <option value="к.к. Елените">к.к. Елените
            <option value="к.к. Слънчев бряг">к.к. Слънчев бряг
            <option value="магистрала Тракия">магистрала Тракия
            <option value="с. Александрово">с. Александрово
            <option value="с. Аспарухово">с. Аспарухово
            <option value="с. Атия">с. Атия
            <option value="с. Балабанчево">с. Балабанчево
            <option value="с. Баня">с. Баня
            <option value="с. Бата">с. Бата
            <option value="с. Белеврен">с. Белеврен
            <option value="с. Белила">с. Белила
            <option value="с. Белодол">с. Белодол
            <option value="с. Бероново">с. Бероново
            <option value="с. Билка">с. Билка
            <option value="с. Бистрец">с. Бистрец
            <option value="с. Близнак">с. Близнак
            <option value="с. Богданово">с. Богданово
            <option value="с. Босилково">с. Босилково
            <option value="с. Бродилово">с. Бродилово
            <option value="с. Бръшлян">с. Бръшлян
            <option value="с. Българи">с. Българи
            <option value="с. Бяла вода">с. Бяла вода
            <option value="с. Варвара">с. Варвара
            <option value="с. Варовник">с. Варовник
            <option value="с. Ведрово">с. Ведрово
            <option value="с. Везенково">с. Везенково
            <option value="с. Велика">с. Велика
            <option value="с. Велислав">с. Велислав
            <option value="с. Венец">с. Венец
            <option value="с. Веселие">с. Веселие
            <option value="с. Визица">с. Визица
            <option value="с. Винарско">с. Винарско
            <option value="с. Вишна">с. Вишна
            <option value="с. Вратица">с. Вратица
            <option value="с. Вресово">с. Вресово
            <option value="с. Вълчаново">с. Вълчаново
            <option value="с. Вълчин">с. Вълчин
            <option value="с. Вършило">с. Вършило
            <option value="с. Габерово">с. Габерово
            <option value="с. Габър">с. Габър
            <option value="с. Глумче">с. Глумче
            <option value="с. Голямо Буково">с. Голямо Буково
            <option value="с. Горица">с. Горица
            <option value="с. Горно Ябълково">с. Горно Ябълково
            <option value="с. Горово">с. Горово
            <option value="с. Граматиково">с. Граматиково
            <option value="с. Гранитец">с. Гранитец
            <option value="с. Граничар">с. Граничар
            <option value="с. Грозден">с. Грозден
            <option value="с. Гълъбец">с. Гълъбец
            <option value="с. Гюльовца">с. Гюльовца
            <option value="с. Дебелт">с. Дебелт
            <option value="с. Деветак">с. Деветак
            <option value="с. Деветинци">с. Деветинци
            <option value="с. Детелина">с. Детелина
            <option value="с. Добра поляна">с. Добра поляна
            <option value="с. Добриново">с. Добриново
            <option value="с. Добромир">с. Добромир
            <option value="с. Долно Ябълково">с. Долно Ябълково
            <option value="с. Драганци">с. Драганци
            <option value="с. Драгово">с. Драгово
            <option value="с. Драка">с. Драка
            <option value="с. Драчево">с. Драчево
            <option value="с. Дропла">с. Дропла
            <option value="с. Дрянковец">с. Дрянковец
            <option value="с. Дъбник">с. Дъбник
            <option value="с. Дъбовица">с. Дъбовица
            <option value="с. Дъскотна">с. Дъскотна
            <option value="с. Дюлево">с. Дюлево
            <option value="с. Дюля">с. Дюля
            <option value="с. Евренозово">с. Евренозово
            <option value="с. Екзарх Антимово">с. Екзарх Антимово
            <option value="с. Емона">с. Емона
            <option value="с. Есен">с. Есен
            <option value="с. Железник">с. Железник
            <option value="с. Желязово">с. Желязово
            <option value="с. Житосвят">с. Житосвят
            <option value="с. Заберново">с. Заберново
            <option value="с. Завет">с. Завет
            <option value="с. Загорци">с. Загорци
            <option value="с. Заимчево">с. Заимчево
            <option value="с. Зайчар">с. Зайчар
            <option value="с. Звезда">с. Звезда
            <option value="с. Звездец">с. Звездец
            <option value="с. Зетьово">с. Зетьово
            <option value="с. Зидарово">с. Зидарово
            <option value="с. Зимен">с. Зимен
            <option value="с. Зорница">с. Зорница
            <option value="с. Изгрев">с. Изгрев
            <option value="с. Индже войвода">с. Индже войвода
            <option value="с. Искра">с. Искра
            <option value="с. Калово">с. Калово
            <option value="с. Каменар">с. Каменар
            <option value="с. Каменско">с. Каменско
            <option value="с. Каменяк">с. Каменяк
            <option value="с. Камчия">с. Камчия
            <option value="с. Каравельово">с. Каравельово
            <option value="с. Карагеоргиево">с. Карагеоргиево
            <option value="с. Караново">с. Караново
            <option value="с. Кирово">с. Кирово
            <option value="с. Китка">с. Китка
            <option value="с. Кликач">с. Кликач
            <option value="с. Климаш">с. Климаш
            <option value="с. Козаре">с. Козаре
            <option value="с. Козичино">с. Козичино
            <option value="с. Козница">с. Козница
            <option value="с. Кондолово">с. Кондолово
            <option value="с. Константиново">с. Константиново
            <option value="с. Косовец">с. Косовец
            <option value="с. Костен">с. Костен
            <option value="с. Кости">с. Кости
            <option value="с. Кошарица">с. Кошарица
            <option value="с. Крумово градище">с. Крумово градище
            <option value="с. Крушевец">с. Крушевец
            <option value="с. Крушово">с. Крушово
            <option value="с. Кръстина">с. Кръстина
            <option value="с. Кубадин">с. Кубадин
            <option value="с. Ливада">с. Ливада
            <option value="с. Листец">с. Листец
            <option value="с. Лозарево">с. Лозарево
            <option value="с. Лозенец">с. Лозенец
            <option value="с. Лозица">с. Лозица
            <option value="с. Лъка">с. Лъка
            <option value="с. Люляково">с. Люляково
            <option value="с. Лясково">с. Лясково
            <option value="с. Малина">с. Малина
            <option value="с. Малка поляна">с. Малка поляна
            <option value="с. Манолич">с. Манолич
            <option value="с. Медово">с. Медово
            <option value="с. Младежко">с. Младежко
            <option value="с. Момина църква">с. Момина църква
            <option value="с. Мрежичко">с. Мрежичко
            <option value="с. Мъглен">с. Мъглен
            <option value="с. Мъдрино">с. Мъдрино
            <option value="с. Невестино">с. Невестино
            <option value="с. Ново Паничарево">с. Ново Паничарево
            <option value="с. Огнен">с. Огнен
            <option value="с. Оризаре">с. Оризаре
            <option value="с. Орлинци">с. Орлинци
            <option value="с. Паницово">с. Паницово
            <option value="с. Пещерско">с. Пещерско
            <option value="с. Пирне">с. Пирне
            <option value="с. Писменово">с. Писменово
            <option value="с. Планиница">с. Планиница
            <option value="с. Подвис">с. Подвис
            <option value="с. Подгорец">с. Подгорец
            <option value="с. Полски извор">с. Полски извор
            <option value="с. Поляново">с. Поляново
            <option value="с. Порой">с. Порой
            <option value="с. Преображенци">с. Преображенци
            <option value="с. Прилеп">с. Прилеп
            <option value="с. Припек">с. Припек
            <option value="с. Присад">с. Присад
            <option value="с. Приселци">с. Приселци
            <option value="с. Просеник">с. Просеник
            <option value="с. Проход">с. Проход
            <option value="с. Пчелин">с. Пчелин
            <option value="с. Пънчево">с. Пънчево
            <option value="с. Равадиново">с. Равадиново
            <option value="с. Равда">с. Равда
            <option value="с. Равна гора">с. Равна гора
            <option value="с. Радойново">с. Радойново
            <option value="с. Разбойна">с. Разбойна
            <option value="с. Раклиново">с. Раклиново
            <option value="с. Раклица">с. Раклица
            <option value="с. Раковсково">с. Раковсково
            <option value="с. Резово">с. Резово
            <option value="с. Речица">с. Речица
            <option value="с. Рожден">с. Рожден
            <option value="с. Росен">с. Росен
            <option value="с. Росеново">с. Росеново
            <option value="с. Рудина">с. Рудина
            <option value="с. Руен">с. Руен
            <option value="с. Рупча">с. Рупча
            <option value="с. Русокастро">с. Русокастро
            <option value="с. Ръжица">с. Ръжица
            <option value="с. Садово">с. Садово
            <option value="с. Сан-Стефано">с. Сан-Стефано
            <option value="с. Светлина">с. Светлина
            <option value="с. Свобода">с. Свобода
            <option value="с. Сигмен">с. Сигмен
            <option value="с. Синеморец">с. Синеморец
            <option value="с. Сини рид">с. Сини рид
            <option value="с. Синьо камене">с. Синьо камене
            <option value="с. Скала">с. Скала
            <option value="с. Скалак">с. Скалак
            <option value="с. Славянци">с. Славянци
            <option value="с. Сливарово">с. Сливарово
            <option value="с. Сливово">с. Сливово
            <option value="с. Смолник">с. Смолник
            <option value="с. Снежа">с. Снежа
            <option value="с. Снягово">с. Снягово
            <option value="с. Соколец">с. Соколец
            <option value="с. Соколово">с. Соколово
            <option value="с. Средна махала">с. Средна махала
            <option value="с. Стоилово">с. Стоилово
            <option value="с. Страцин">с. Страцин
            <option value="с. Струя">с. Струя
            <option value="с. Суходол">с. Суходол
            <option value="с. Съдиево">с. Съдиево
            <option value="с. Съединение">с. Съединение
            <option value="с. Сърнево">с. Сърнево
            <option value="с. Терзийско">с. Терзийско
            <option value="с. Тополица">с. Тополица
            <option value="с. Топчийско">с. Топчийско
            <option value="с. Тракийци">с. Тракийци
            <option value="с. Трояново">с. Трояново
            <option value="с. Трънак">с. Трънак
            <option value="с. Тръстиково">с. Тръстиково
            <option value="с. Тънково">с. Тънково
            <option value="с. Фазаново">с. Фазаново
            <option value="с. Факия">с. Факия
            <option value="с. Хаджиите">с. Хаджиите
            <option value="с. Церковски">с. Церковски
            <option value="с. Череша">с. Череша
            <option value="с. Черково">с. Черково
            <option value="с. Черна могила">с. Черна могила
            <option value="с. Черни връх">с. Черни връх
            <option value="с. Черница">с. Черница
            <option value="с. Черноград">с. Черноград
            <option value="с. Чубра">с. Чубра
            <option value="с. Чукарка">с. Чукарка
            <option value="с. Шиварово">с. Шиварово
            <option value="с. Ябълчево">с. Ябълчево
            <option value="с. Ясеново">с. Ясеново
            <option value="с. Ясна поляна">с. Ясна поляна`
        break;

        case 'tvarna':
            townArea.innerHTML = `
            <option value="Автогара">Автогара
            <option value="Аспарухово">Аспарухово
            <option value="Базар Левски">Базар Левски
            <option value="Бизнес парк Варна">Бизнес парк Варна
            <option value="Бизнес хотел">Бизнес хотел
            <option value="Бриз">Бриз
            <option value="Виница">Виница
            <option value="ВИНС-Червен площад">ВИНС-Червен площад
            <option value="Владислав Варненчик 1">Владислав Варненчик 1
            <option value="Владислав Варненчик 2">Владислав Варненчик 2
            <option value="Възраждане 1">Възраждане 1
            <option value="Възраждане 2">Възраждане 2
            <option value="Възраждане 3">Възраждане 3
            <option value="Възраждане 4">Възраждане 4
            <option value="Галата">Галата
            <option value="Гранд Мол">Гранд Мол
            <option value="Гръцка махала">Гръцка махала
            <option value="Електроразпределение Варна">Електроразпределение Варна
            <option value="ЖП Гара">ЖП Гара
            <option value="Завод Дружба">Завод Дружба
            <option value="Западна промишлена зона">Западна промишлена зона
            <option value="Зимно кино Тракия">Зимно кино Тракия
            <option value="Изгрев">Изгрев
            <option value="Кайсиева градина">Кайсиева градина
            <option value="Колхозен пазар">Колхозен пазар
            <option value="Конфуто">Конфуто
            <option value="Левски 1">Левски 1
            <option value="Левски 2">Левски 2
            <option value="Летище">Летище
            <option value="Лятно кино Тракия">Лятно кино Тракия
            <option value="Максуда">Максуда
            <option value="Малка Чайка">Малка Чайка
            <option value="Метро">Метро
            <option value="Младост 1">Младост 1
            <option value="Младост 2">Младост 2
            <option value="Окръжна болница-Генерали">Окръжна болница-Генерали
            <option value="Операта">Операта
            <option value="Островна промишлена зона">Островна промишлена зона
            <option value="Планова промишлена зона">Планова промишлена зона
            <option value="Победа">Победа
            <option value="Погреби">Погреби
            <option value="Пристанище Варна">Пристанище Варна
            <option value="Промишлена зона Тополи">Промишлена зона Тополи
            <option value="Свети Никола">Свети Никола
            <option value="Северна промишлена зона">Северна промишлена зона
            <option value="Спортна зала">Спортна зала
            <option value="Стадион Спартак">Стадион Спартак
            <option value="Трошево">Трошево
            <option value="Фестивален комплекс">Фестивален комплекс
            <option value="ХЕИ">ХЕИ
            <option value="Христо Ботев">Христо Ботев
            <option value="Цветен квартал">Цветен квартал
            <option value="Централна поща">Централна поща
            <option value="Център">Център
            <option value="Чайка">Чайка
            <option value="Чаталджа">Чаталджа
            <option value="в.з.Виница - север">в.з.Виница - север
            <option value="в.з.Звездица">в.з.Звездица
            <option value="к.к. Златни пясъци">к.к. Златни пясъци
            <option value="к.к. Св.Св. Константин и Елена">к.к. Св.Св. Константин и Елена
            <option value="к.к. Слънчев ден">к.к. Слънчев ден
            <option value="к.к. Чайка">к.к. Чайка
            <option value="м-т Акчелар">м-т Акчелар
            <option value="м-т Ален мак">м-т Ален мак
            <option value="м-т Атанас Тарла">м-т Атанас Тарла
            <option value="м-т Балам Дере">м-т Балам Дере
            <option value="м-т Боклук Тарла">м-т Боклук Тарла
            <option value="м-т Боровец - север">м-т Боровец - север
            <option value="м-т Боровец - юг">м-т Боровец - юг
            <option value="м-т Горна Трака">м-т Горна Трака
            <option value="м-т Добрева чешма">м-т Добрева чешма
            <option value="м-т Долна Трака">м-т Долна Трака
            <option value="м-т Евксиноград">м-т Евксиноград
            <option value="м-т Зеленика">м-т Зеленика
            <option value="м-т Кантара">м-т Кантара
            <option value="м-т Кочмар">м-т Кочмар
            <option value="м-т Крушките">м-т Крушките
            <option value="м-т Лазур">м-т Лазур
            <option value="м-т Манастирски рид">м-т Манастирски рид
            <option value="м-т Ментешето">м-т Ментешето
            <option value="м-т Орехчето">м-т Орехчето
            <option value="м-т Перчемлията">м-т Перчемлията
            <option value="м-т Планова">м-т Планова
            <option value="м-т Прибой">м-т Прибой
            <option value="м-т Припек">м-т Припек
            <option value="м-т Пчелина">м-т Пчелина
            <option value="м-т Ракитника">м-т Ракитника
            <option value="м-т Салтанат">м-т Салтанат
            <option value="м-т Сотира">м-т Сотира
            <option value="м-т Сълзица">м-т Сълзица
            <option value="м-т Телевизионна кула">м-т Телевизионна кула
            <option value="м-т Фичоза">м-т Фичоза
            <option value="м-т Франга Дере">м-т Франга Дере
            <option value="с. Звездица">с. Звездица
            <option value="с. Казашко">с. Казашко
            <option value="с. Каменар">с. Каменар
            <option value="с. Константиново">с. Константиново
            <option value="с. Тополи">с. Тополи
            `
            break;

            case 'pvarna':
                townArea.innerHTML = `
                <option value="гр. Аксаково">гр. Аксаково
                <option value="гр. Белослав">гр. Белослав
                <option value="гр. Бяла">гр. Бяла
                <option value="гр. Вълчи дол">гр. Вълчи дол
                <option value="гр. Девня">гр. Девня
                <option value="гр. Долни чифлик">гр. Долни чифлик
                <option value="гр. Дългопол">гр. Дългопол
                <option value="гр. Игнатиево">гр. Игнатиево
                <option value="гр. Провадия">гр. Провадия
                <option value="гр. Суворово">гр. Суворово
                <option value="к.к. Камчия">к.к. Камчия
                <option value="с. Аврен">с. Аврен
                <option value="с. Арковна">с. Арковна
                <option value="с. Аспарухово">с. Аспарухово
                <option value="с. Баново">с. Баново
                <option value="с. Белоградец">с. Белоградец
                <option value="с. Бенковски">с. Бенковски
                <option value="с. Близнаци">с. Близнаци
                <option value="с. Блъсково">с. Блъсково
                <option value="с. Бозвелийско">с. Бозвелийско
                <option value="с. Болярци">с. Болярци
                <option value="с. Боряна">с. Боряна
                <option value="с. Ботево">с. Ботево
                <option value="с. Бояна">с. Бояна
                <option value="с. Брестак">с. Брестак
                <option value="с. Булаир">с. Булаир
                <option value="с. Бърдарево">с. Бърдарево
                <option value="с. Бързица">с. Бързица
                <option value="с. Величково">с. Величково
                <option value="с. Венелин">с. Венелин
                <option value="с. Венчан">с. Венчан
                <option value="с. Ветрино">с. Ветрино
                <option value="с. Водица">с. Водица
                <option value="с. Войводино">с. Войводино
                <option value="с. Въглен">с. Въглен
                <option value="с. Габърница">с. Габърница
                <option value="с. Генерал Кантарджиево">с. Генерал Кантарджиево
                <option value="с. Генерал Киселово">с. Генерал Киселово
                <option value="с. Генерал Колево">с. Генерал Колево
                <option value="с. Голица">с. Голица
                <option value="с. Горен чифлик">с. Горен чифлик
                <option value="с. Горица">с. Горица
                <option value="с. Господиново">с. Господиново
                <option value="с. Градинарово">с. Градинарово
                <option value="с. Гроздьово">с. Гроздьово
                <option value="с. Дебелец">с. Дебелец
                <option value="с. Детелина">с. Детелина
                <option value="с. Добри дол">с. Добри дол
                <option value="с. Добрина">с. Добрина
                <option value="с. Доброглед">с. Доброглед
                <option value="с. Доброплодно">с. Доброплодно
                <option value="с. Добротич">с. Добротич
                <option value="с. Долище">с. Долище
                <option value="с. Дръндар">с. Дръндар
                <option value="с. Дъбравино">с. Дъбравино
                <option value="с. Дюлино">с. Дюлино
                <option value="с. Езерово">с. Езерово
                <option value="с. Есеница">с. Есеница
                <option value="с. Житница">с. Житница
                <option value="с. Засмяно">с. Засмяно
                <option value="с. Звънец">с. Звънец
                <option value="с. Здравец">с. Здравец
                <option value="с. Златина">с. Златина
                <option value="с. Зорница">с. Зорница
                <option value="с. Изворник">с. Изворник
                <option value="с. Изворско">с. Изворско
                <option value="с. Изгрев">с. Изгрев
                <option value="с. Искър">с. Искър
                <option value="с. Казашка река">с. Казашка река
                <option value="с. Калиманци">с. Калиманци
                <option value="с. Калоян">с. Калоян
                <option value="с. Камен дял">с. Камен дял
                <option value="с. Караманите">с. Караманите
                <option value="с. Кипра">с. Кипра
                <option value="с. Китен">с. Китен
                <option value="с. Китка">с. Китка
                <option value="с. Кичево">с. Кичево
                <option value="с. Климентово">с. Климентово
                <option value="с. Комарево">с. Комарево
                <option value="с. Комунари">с. Комунари
                <option value="с. Кракра">с. Кракра
                <option value="с. Красимир">с. Красимир
                <option value="с. Кривини">с. Кривини
                <option value="с. Кривня">с. Кривня
                <option value="с. Крумово">с. Крумово
                <option value="с. Круша">с. Круша
                <option value="с. Куманово">с. Куманово
                <option value="с. Левски">с. Левски
                <option value="с. Лопушна">с. Лопушна
                <option value="с. Любен Каравелово">с. Любен Каравелово
                <option value="с. Манастир">с. Манастир
                <option value="с. Медовец">с. Медовец
                <option value="с. Метличина">с. Метличина
                <option value="с. Михалич">с. Михалич
                <option value="с. Млада гвардия">с. Млада гвардия
                <option value="с. Момчилово">с. Момчилово
                <option value="с. Невша">с. Невша
                <option value="с. Неново">с. Неново
                <option value="с. Неофит Рилски">с. Неофит Рилски
                <option value="с. Николаевка">с. Николаевка
                <option value="с. Нова Шипка">с. Нова Шипка
                <option value="с. Новаково">с. Новаково
                <option value="с. Ново Оряхово">с. Ново Оряхово
                <option value="с. Оборище">с. Оборище
                <option value="с. Овчага">с. Овчага
                <option value="с. Орешак">с. Орешак
                <option value="с. Осеново">с. Осеново
                <option value="с. Падина">с. Падина
                <option value="с. Партизани">с. Партизани
                <option value="с. Петров дол">с. Петров дол
                <option value="с. Поляците">с. Поляците
                <option value="с. Попович">с. Попович
                <option value="с. Припек">с. Припек
                <option value="с. Приселци">с. Приселци
                <option value="с. Просечен">с. Просечен
                <option value="с. Пчелник">с. Пчелник
                <option value="с. Равна">с. Равна
                <option value="с. Равна гора">с. Равна гора
                <option value="с. Радан войвода">с. Радан войвода
                <option value="с. Радево">с. Радево
                <option value="с. Разделна">с. Разделна
                <option value="с. Рояк">с. Рояк
                <option value="с. Рудник">с. Рудник
                <option value="с. Сава">с. Сава
                <option value="с. Садово">с. Садово
                <option value="с. Самотино">с. Самотино
                <option value="с. Синдел">с. Синдел
                <option value="с. Славейково">с. Славейково
                <option value="с. Сладка вода">с. Сладка вода
                <option value="с. Слънчево">с. Слънчево
                <option value="с. Снежина">с. Снежина
                <option value="с. Солник">с. Солник
                <option value="с. Средно село">с. Средно село
                <option value="с. Старо Оряхово">с. Старо Оряхово
                <option value="с. Староселец">с. Староселец
                <option value="с. Стефан Караджа">с. Стефан Караджа
                <option value="с. Страхил">с. Страхил
                <option value="с. Страшимирово">с. Страшимирово
                <option value="с. Тръстиково">с. Тръстиково
                <option value="с. Тутраканци">с. Тутраканци
                <option value="с. Храброво">с. Храброво
                <option value="с. Царевци">с. Царевци
                <option value="с. Цонево">с. Цонево
                <option value="с. Чайка">с. Чайка
                <option value="с. Червенци">с. Червенци
                <option value="с. Черковна">с. Черковна
                <option value="с. Чернево">с. Чернево
                <option value="с. Черноок">с. Черноок
                <option value="с. Шкорпиловци">с. Шкорпиловци
                <option value="с. Щипско">с. Щипско
                <option value="с. Юнак">с. Юнак
                <option value="с. Юнец">с. Юнец
                <option value="с. Ягнило">с. Ягнило
                <option value="с. Яребична">с. Яребична
                <option value="яз. Цонево">яз. Цонево
                
                `
            break;

            case 'tvt':
                townArea.innerHTML = `
                <option value="Акация">Акация
                <option value="Асенов">Асенов
                <option value="Бузлуджа">Бузлуджа
                <option value="Варуша">Варуша
                <option value="Зона Б">Зона Б
                <option value="Картала">Картала
                <option value="Колю Фичето">Колю Фичето
                <option value="Промишлена зона - Запад">Промишлена зона - Запад
                <option value="Промишлена зона - Юг">Промишлена зона - Юг
                <option value="Света гора">Света гора
                <option value="Стара част">Стара част
                <option value="Централна гара">Централна гара
                <option value="Център">Център
                <option value="Чолаковци">Чолаковци
                <option value="м-т Козлуджа">м-т Козлуджа      
                `
            break;

            case 'pvt':
                townArea.innerHTML = `
                <option value="главен път Е83">главен път Е83
                <option value="главен път Е85">главен път Е85
                <option value="гр. Бяла черква">гр. Бяла черква
                <option value="гр. Горна Оряховица">гр. Горна Оряховица
                <option value="гр. Дебелец">гр. Дебелец
                <option value="гр. Долна Оряховица">гр. Долна Оряховица
                <option value="гр. Елена">гр. Елена
                <option value="гр. Златарица">гр. Златарица
                <option value="гр. Килифарево">гр. Килифарево
                <option value="гр. Лясковец">гр. Лясковец
                <option value="гр. Павликени">гр. Павликени
                <option value="гр. Полски Тръмбеш">гр. Полски Тръмбеш
                <option value="гр. Свищов">гр. Свищов
                <option value="гр. Стражица">гр. Стражица
                <option value="гр. Сухиндол">гр. Сухиндол
                <option value="с. Алеково">с. Алеково
                <option value="с. Александрово">с. Александрово
                <option value="с. Аплаци">с. Аплаци
                <option value="с. Арбанаси">с. Арбанаси
                <option value="с. Асеново">с. Асеново
                <option value="с. Багалевци">с. Багалевци
                <option value="с. Бадевци">с. Бадевци
                <option value="с. Баевци">с. Баевци
                <option value="с. Баждари">с. Баждари
                <option value="с. Балван">с. Балван
                <option value="с. Балканци">с. Балканци
                <option value="с. Балуци">с. Балуци
                <option value="с. Батак">с. Батак
                <option value="с. Беброво">с. Беброво
                <option value="с. Бейковци">с. Бейковци
                <option value="с. Белчевци">с. Белчевци
                <option value="с. Беляковец">с. Беляковец
                <option value="с. Берковци">с. Берковци
                <option value="с. Бижовци">с. Бижовци
                <option value="с. Благоево">с. Благоево
                <option value="с. Блъсковци">с. Блъсковци
                <option value="с. Богданско">с. Богданско
                <option value="с. Бойковци">с. Бойковци
                <option value="с. Бойчеви колиби">с. Бойчеви колиби
                <option value="с. Бойчовци">с. Бойчовци
                <option value="с. Босевци">с. Босевци
                <option value="с. Бочковци">с. Бочковци
                <option value="с. Бояновци">с. Бояновци
                <option value="с. Бранковци">с. Бранковци
                <option value="с. Брезово">с. Брезово
                <option value="с. Бръчковци">с. Бръчковци
                <option value="с. Бряговица">с. Бряговица
                <option value="с. Буйновци">с. Буйновци
                <option value="с. Буковец">с. Буковец
                <option value="с. Бутово">с. Бутово
                <option value="с. Българско Сливово">с. Българско Сливово
                <option value="с. Бяла река">с. Бяла река
                <option value="с. Бялковци">с. Бялковци
                <option value="с. Валето">с. Валето
                <option value="с. Вардим">с. Вардим
                <option value="с. Велковци">с. Велковци
                <option value="с. Велчево">с. Велчево
                <option value="с. Велювци">с. Велювци
                <option value="с. Веселина">с. Веселина
                <option value="с. Ветринци">с. Ветринци
                <option value="с. Виларе">с. Виларе
                <option value="с. Виноград">с. Виноград
                <option value="с. Високовци">с. Високовци
                <option value="с. Вишовград">с. Вишовград
                <option value="с. Владислав">с. Владислав
                <option value="с. Водно">с. Водно
                <option value="с. Водолей">с. Водолей
                <option value="с. Войнежа">с. Войнежа
                <option value="с. Вонеща вода">с. Вонеща вода
                <option value="с. Въглевци">с. Въглевци
                <option value="с. Вълчовци">с. Вълчовци
                <option value="с. Върбица">с. Върбица
                <option value="с. Върбовка">с. Върбовка
                <option value="с. Вързилковци">с. Вързилковци
                <option value="с. Вързулица">с. Вързулица
                <option value="с. Върлинка">с. Върлинка
                <option value="с. Габрака">с. Габрака
                <option value="с. Габровци">с. Габровци
                <option value="с. Ганев дол">с. Ганев дол
                <option value="с. Гащевци">с. Гащевци
                <option value="с. Глоговец">с. Глоговец
                <option value="с. Големани">с. Големани
                <option value="с. Големаните">с. Големаните
                <option value="с. Горановци">с. Горановци
                <option value="с. Горен Еневец">с. Горен Еневец
                <option value="с. Горна Липница">с. Горна Липница
                <option value="с. Горна Студена">с. Горна Студена
                <option value="с. Горна Хаджийска">с. Горна Хаджийска
                <option value="с. Горни край">с. Горни край
                <option value="с. Горни Танчевци">с. Горни Танчевци
                <option value="с. Горска">с. Горска
                <option value="с. Горски горен Тръмбеш">с. Горски горен Тръмбеш
                <option value="с. Горски долен Тръмбеш">с. Горски долен Тръмбеш
                <option value="с. Горски Сеновец">с. Горски Сеновец
                <option value="с. Горско Калугерово">с. Горско Калугерово
                <option value="с. Горско Косово">с. Горско Косово
                <option value="с. Горско ново село">с. Горско ново село
                <option value="с. Горско Писарево">с. Горско Писарево
                <option value="с. Граматици">с. Граматици
                <option value="с. Гърдевци">с. Гърдевци
                <option value="с. Давери">с. Давери
                <option value="с. Дайновци">с. Дайновци
                <option value="с. Дебели рът">с. Дебели рът
                <option value="с. Деветаците">с. Деветаците
                <option value="с. Дедина">с. Дедина
                <option value="с. Дединци">с. Дединци
                <option value="с. Делова махала">с. Делова махала
                <option value="с. Деляновци">с. Деляновци
                <option value="с. Джулюница">с. Джулюница
                <option value="с. Димитровци">с. Димитровци
                <option value="с. Димовци">с. Димовци
                <option value="с. Димча">с. Димча
                <option value="с. Дичин">с. Дичин
                <option value="с. Добревци">с. Добревци
                <option value="с. Добри дял">с. Добри дял
                <option value="с. Дойновци">с. Дойновци
                <option value="с. Долен Еневец">с. Долен Еневец
                <option value="с. Долна Липница">с. Долна Липница
                <option value="с. Долни Дамяновци">с. Долни Дамяновци
                <option value="с. Долни Марян">с. Долни Марян
                <option value="с. Долни Танчевци">с. Долни Танчевци
                <option value="с. Долно Шивачево">с. Долно Шивачево
                <option value="с. Донковци">с. Донковци
                <option value="с. Драганово">с. Драганово
                <option value="с. Драгановци">с. Драгановци
                <option value="с. Драганосковци">с. Драганосковци
                <option value="с. Драгижево">с. Драгижево
                <option value="с. Драгийци">с. Драгийци
                <option value="с. Драгневци">с. Драгневци
                <option value="с. Драгомирово">с. Драгомирово
                <option value="с. Дрента">с. Дрента
                <option value="с. Дуковци">с. Дуковци
                <option value="с. Дунавци">с. Дунавци
                <option value="с. Дуровци">с. Дуровци
                <option value="с. Дълги припек">с. Дълги припек
                <option value="с. Дърлевци">с. Дърлевци
                <option value="с. Дъскот">с. Дъскот
                <option value="с. Емен">с. Емен
                <option value="с. Железарци">с. Железарци
                <option value="с. Зеленик">с. Зеленик
                <option value="с. Иванивановци">с. Иванивановци
                <option value="с. Ивановци">с. Ивановци
                <option value="с. Иванча">с. Иванча
                <option value="с. Игнатовци">с. Игнатовци
                <option value="с. Илаков рът">с. Илаков рът
                <option value="с. Илевци">с. Илевци
                <option value="с. Илиювци">с. Илиювци
                <option value="с. Йовчевци">с. Йовчевци
                <option value="с. Кавлак">с. Кавлак
                <option value="с. Калайджии">с. Калайджии
                <option value="с. Камен">с. Камен
                <option value="с. Каменари">с. Каменари
                <option value="с. Кантари">с. Кантари
                <option value="с. Караиванци">с. Караиванци
                <option value="с. Караисен">с. Караисен
                <option value="с. Карандили">с. Карандили
                <option value="с. Каранци">с. Каранци
                <option value="с. Кесарево">с. Кесарево
                <option value="с. Киревци">с. Киревци
                <option value="с. Кисьовци">с. Кисьовци
                <option value="с. Кладни дял">с. Кладни дял
                <option value="с. Климентово">с. Климентово
                <option value="с. Клъшка река">с. Клъшка река
                <option value="с. Коевци">с. Коевци
                <option value="с. Кожлювци">с. Кожлювци
                <option value="с. Козаревец">с. Козаревец
                <option value="с. Козловец">с. Козловец
                <option value="с. Козя река">с. Козя река
                <option value="с. Колари">с. Колари
                <option value="с. Константин">с. Константин
                <option value="с. Косевци">с. Косевци
                <option value="с. Костел">с. Костел
                <option value="с. Котуци">с. Котуци
                <option value="с. Красно градище">с. Красно градище
                <option value="с. Крилювци">с. Крилювци
                <option value="с. Крумчевци">с. Крумчевци
                <option value="с. Крушето">с. Крушето
                <option value="с. Куцаровци">с. Куцаровци
                <option value="с. Куцина">с. Куцина
                <option value="с. Къпиново">с. Къпиново
                <option value="с. Лагерите">с. Лагерите
                <option value="с. Лазарци">с. Лазарци
                <option value="с. Леденик">с. Леденик
                <option value="с. Лесиче">с. Лесиче
                <option value="с. Лесичери">с. Лесичери
                <option value="с. Лозен">с. Лозен
                <option value="с. Любенци">с. Любенци
                <option value="с. Майско">с. Майско
                <option value="с. Малки чифлик">с. Малки чифлик
                <option value="с. Малчовци">с. Малчовци
                <option value="с. Марафелци">с. Марафелци
                <option value="с. Марговци">с. Марговци
                <option value="с. Мариновци">с. Мариновци
                <option value="с. Марян">с. Марян
                <option value="с. Масларево">с. Масларево
                <option value="с. Махалници">с. Махалници
                <option value="с. Мерданя">с. Мерданя
                <option value="с. Мийковци">с. Мийковци
                <option value="с. Миндя">с. Миндя
                <option value="с. Миневци">с. Миневци
                <option value="с. Мирово">с. Мирово
                <option value="с. Мирчовци">с. Мирчовци
                <option value="с. Михалци">с. Михалци
                <option value="с. Мишеморков хан">с. Мишеморков хан
                <option value="с. Момин сбор">с. Момин сбор
                <option value="с. Морава">с. Морава
                <option value="с. Мусина">с. Мусина
                <option value="с. Мъртвината">с. Мъртвината
                <option value="с. Нацовци">с. Нацовци
                <option value="с. Недан">с. Недан
                <option value="с. Недялковци">с. Недялковци
                <option value="с. Нешевци">с. Нешевци
                <option value="с. Николаево">с. Николаево
                <option value="с. Николовци">с. Николовци
                <option value="с. Николчовци">с. Николчовци
                <option value="с. Никюп">с. Никюп
                <option value="с. Ничовци">с. Ничовци
                <option value="с. Нова Върбовка">с. Нова Върбовка
                <option value="с. Ново градище">с. Ново градище
                <option value="с. Ново село">с. Ново село
                <option value="с. Новогорци">с. Новогорци
                <option value="с. Нюшковци">с. Нюшковци
                <option value="с. Обединение">с. Обединение
                <option value="с. Овощна">с. Овощна
                <option value="с. Овча могила">с. Овча могила
                <option value="с. Ореш">с. Ореш
                <option value="с. Орловец">с. Орловец
                <option value="с. Осенарите">с. Осенарите
                <option value="с. Павел">с. Павел
                <option value="с. Паисий">с. Паисий
                <option value="с. Палици">с. Палици
                <option value="с. Папратлива">с. Папратлива
                <option value="с. Паскалевец">с. Паскалевец
                <option value="с. Патреш">с. Патреш
                <option value="с. Пейковци">с. Пейковци
                <option value="с. Петко Каравелово">с. Петко Каравелово
                <option value="с. Петковци">с. Петковци
                <option value="с. Пирамидата">с. Пирамидата
                <option value="с. Писарево">с. Писарево
                <option value="с. Плаково">с. Плаково
                <option value="с. Пожерник">с. Пожерник
                <option value="с. Поликраище">с. Поликраище
                <option value="с. Полски Сеновец">с. Полски Сеновец
                <option value="с. Поповци">с. Поповци
                <option value="с. Попрусевци">с. Попрусевци
                <option value="с. Попска">с. Попска
                <option value="с. Правда">с. Правда
                <option value="с. Присово">с. Присово
                <option value="с. Продановци">с. Продановци
                <option value="с. Пушево">с. Пушево
                <option value="с. Пчелище">с. Пчелище
                <option value="с. Първомайци">с. Първомайци
                <option value="с. Пъровци">с. Пъровци
                <option value="с. Равново">с. Равново
                <option value="с. Раданово">с. Раданово
                <option value="с. Радковци">с. Радковци
                <option value="с. Радовци">с. Радовци
                <option value="с. Разсоха">с. Разсоха
                <option value="с. Райковци">с. Райковци
                <option value="с. Райновци">с. Райновци
                <option value="с. Ралиновци">с. Ралиновци
                <option value="с. Рашевци">с. Рашевци
                <option value="с. Раювци">с. Раювци
                <option value="с. Ребревци">с. Ребревци
                <option value="с. Резач">с. Резач
                <option value="с. Рекичка">с. Рекичка
                <option value="с. Ресен">с. Ресен
                <option value="с. Родина">с. Родина
                <option value="с. Росица">с. Росица
                <option value="с. Росно">с. Росно
                <option value="с. Русаля">с. Русаля
                <option value="с. Русковци">с. Русковци
                <option value="с. Руховци">с. Руховци
                <option value="с. Самоводене">с. Самоводене
                <option value="с. Самсиите">с. Самсиите
                <option value="с. Светославци">с. Светославци
                <option value="с. Сеймените">с. Сеймените
                <option value="с. Семковци">с. Семковци
                <option value="с. Сливовица">с. Сливовица
                <option value="с. Сломер">с. Сломер
                <option value="с. Совата">с. Совата
                <option value="с. Средни колиби">с. Средни колиби
                <option value="с. Средно село">с. Средно село
                <option value="с. Стамболово">с. Стамболово
                <option value="с. Стефан Стамболово">с. Стефан Стамболово
                <option value="с. Стойчевци">с. Стойчевци
                <option value="с. Стояновци">с. Стояновци
                <option value="с. Страхилово">с. Страхилово
                <option value="с. Стрелец">с. Стрелец
                <option value="с. Султани">с. Султани
                <option value="с. Суха река">с. Суха река
                <option value="с. Сушица">с. Сушица
                <option value="с. Събковци">с. Събковци
                <option value="с. Сърненци">с. Сърненци
                <option value="с. Теменуга">с. Теменуга
                <option value="с. Терзиите">с. Терзиите
                <option value="с. Титевци">с. Титевци
                <option value="с. Тодоровци">с. Тодоровци
                <option value="с. Тодювци">с. Тодювци
                <option value="с. Томбето">с. Томбето
                <option value="с. Топузи">с. Топузи
                <option value="с. Трънковци">с. Трънковци
                <option value="с. Тумбевци">с. Тумбевци
                <option value="с. Тънки рът">с. Тънки рът
                <option value="с. Търкашени">с. Търкашени
                <option value="с. Угорялковци">с. Угорялковци
                <option value="с. Ушeвци">с. Ушeвци
                <option value="с. Хаджидимитрово">с. Хаджидимитрово
                <option value="с. Харваловци">с. Харваловци
                <option value="с. Хотница">с. Хотница
                <option value="с. Христовци">с. Христовци
                <option value="с. Хъневци">с. Хъневци
                <option value="с. Царевец">с. Царевец
                <option value="с. Царски извор">с. Царски извор
                <option value="с. Цвеклювци">с. Цвеклювци
                <option value="с. Цепераните">с. Цепераните
                <option value="с. Церова кория">с. Церова кория
                <option value="с. Цонковци">с. Цонковци
                <option value="с. Чавдарци">с. Чавдарци
                <option value="с. Чакали">с. Чакали
                <option value="с. Червена">с. Червена
                <option value="с. Червенковци">с. Червенковци
                <option value="с. Черни дял">с. Черни дял
                <option value="с. Чешма">с. Чешма
                <option value="с. Чистово">с. Чистово
                <option value="с. Чуката">с. Чуката
                <option value="с. Шемшево">с. Шемшево
                <option value="с. Шереметя">с. Шереметя
                <option value="с. Шиливери">с. Шиливери
                <option value="с. Шилковци">с. Шилковци
                <option value="с. Шодековци">с. Шодековци
                <option value="с. Шубеци">с. Шубеци
                <option value="с. Яковци">с. Яковци
                <option value="с. Ялово">с. Ялово
                <option value="с. Янтра">с. Янтра
                <option value="яз. Ал. Стамболийски">яз. Ал. Стамболийски
                `
            break;

            case 'tvidin':
                textArea.innerHTML = `
                <option value="Акджамия">Акджамия
                <option value="Александър Стамболийски">Александър Стамболийски
                <option value="Баба Тонка">Баба Тонка
                <option value="Бонония">Бонония
                <option value="Васил Левски">Васил Левски
                <option value="Вида 1">Вида 1
                <option value="Вида 2">Вида 2
                <option value="Възраждане">Възраждане
                <option value="Гео Милев">Гео Милев
                <option value="Георги Бенковски">Георги Бенковски
                <option value="Калето">Калето
                <option value="Крум Бъчваров">Крум Бъчваров
                <option value="Кумбаир">Кумбаир
                <option value="Нов път">Нов път
                <option value="Панония">Панония
                <option value="Петко Каравелов">Петко Каравелов
                <option value="Плиска">Плиска
                <option value="Промишлена зона">Промишлена зона
                <option value="Промишлена зона - Запад">Промишлена зона - Запад
                <option value="Промишлена зона - Север">Промишлена зона - Север
                <option value="Промишлена зона - Юг">Промишлена зона - Юг
                <option value="Стефан Стамболов">Стефан Стамболов
                <option value="Строител">Строител
                <option value="Съединение">Съединение
                <option value="Химик">Химик
                <option value="Христо Ботев">Христо Ботев
                <option value="Център">Център
                <option value="в.з. Акджамия">в.з. Акджамия
                <option value="в.з. Кумбаир">в.з. Кумбаир
                
                `
            break;

        
    }



}